### ISSUE TITLE
requestLegacyExternalStorage fails for older SDK versions

### ISSUE THREAD

**Issue by MrOneTwo** [cnlohr/rawdrawandroid#11]
```
AndroidManifest.xml:3: error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
```

Deleting that part from the xml *fixes* it. I don't have enough knowledge around Android to know if you can just remove it without consequences. Try on a few SDK versions below 29. Currently on 24 and it fails.

Btw this project is amazing. Every few years I google 'Android + C` and everyone says it's impossible. Heh.

**Comment by cnlohr** [comment]
You cannot remove it if you want to access files at all if targeting Android 29+.  It's frustrating, but, I know no other way forward.  We could make the default target 28, I suppose... But that is absolutely the lowest supported by the store.

**Comment by cnlohr** [comment]
@MrOneTwo if you ever do find a better solution, please feel free to open a new issue, but rest assured, google will find this thread so any poor souls who run past it will see your answer.
