### ISSUE TITLE
push & run aligned apk to device

### ISSUE THREAD

**Issue by GitHubIsToxic** [cnlohr/rawdrawandroid#13]
A few suggestion:

1) Currently, the Makefile installs and runs `makecapk.apk`, wouldn't it be better to replace that with `aligned.apk`?

2) In my modified version of the Makefile I also added ```APK_NAME ?= $(APPNAME).apk``` variable to automatically name the final (aligned) .apk output.

3) Wouldn't it also be cleaner to delete `temp.apk` and `makecapk.apk` (or at least the former) after a successful build? I think it would avoid confusion.

4) I would also replace `echo` with `@echo` to make the output a slight bit easier to parse by eye.

**Comment by cnlohr** [comment]
Hmm... This is attractive.  Do you mind taking the current setup and doing a diff on the Makefile for just this?  I would probably accept it.

**Comment by cnlohr** [comment]
This was also resolved in the recent PR.
