### ISSUE TITLE
( 2621): Asset path /root/android-sdk/platforms/android-29/android.jar is neither a directory nor file (type=1). In windows Linux WSL 

### ISSUE THREAD

**Issue by vijaypanchal** [cnlohr/rawdrawandroid#14]
Resource Dirs:
  Type mipmap
    mipmap/icon.png
      Src: () Sources/res/mipmap/icon.png
  Type values
    values/strings.xml
      Src: () Sources/res/values/strings.xml
Including resources from package: /root/android-sdk/platforms/android-29/android.jar
W/asset   ( 2621): Asset path /root/android-sdk/platforms/android-29/android.jar is neither a directory nor file (type=1).
ERROR: Asset package include '/root/android-sdk/platforms/android-29/android.jar' not found.
Makefile:125: recipe for target 'makecapk.apk' failed
make: *** [makecapk.apk] Error 1

**Comment by GitHubIsToxic** [comment]
Could you try locating the Android SDK directory location on your hard drive? I.e. search for the `android-29/android.jar` file. The SDK/NDK build tools directory may not detected by the Makefile on your setup.

**Comment by cnlohr** [comment]
Also, if you do not have the Android 29 SDK fully installed, rawdrawandroid will be unable to target it.

**Comment by cnlohr** [comment]
I am closing issue for now, if these are sufficient, please re-open the issue.

**Comment by nhobson99** [comment]
I'm also having this problem. I'm running Debian on WSL, and it seems that following the installation in the repo led to only having Android 24 under my Android platforms directory. One thing to note, I had to add -no_https at the end of both sdkmanager steps, which may have fudged the install slightly.
