### ISSUE TITLE
adb fails to collect certificates, even if `make keystore` has already been run 

### ISSUE THREAD

**Issue by Heejintzu** [cnlohr/rawdrawandroid#15]
I'm using the Terminator terminal on Arch Linux. The Java development kit is installed, Android Studio is installed and I followed the setup instructions up until this command below.

Command:
```make push run```

Output:
```
echo "Installing" org.yourorg.cnfgtest
Installing org.yourorg.cnfgtest
adb install makecapk.apk
Performing Streamed Install
adb: failed to install makecapk.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl807465674.tmp/base.apk: Attempt to get length of null array]
make: *** [Makefile:143: push] Error 1

```

**Comment by cnlohr** [comment]
Please try re-running with `make clean run` and posting entire command output.

**Comment by Heejintzu** [comment]
```make clean run`` solves the issue. Apparently there was no keystore before.
