### ISSUE TITLE
Error 1 when reinstalling

### ISSUE THREAD

**Issue by EmmanuelMess** [cnlohr/rawdrawandroid#20]
The app installs, instacrashes, and when I tried to rerun it:

```
adb install cnfgtest.apk
adb: failed to install cnfgtest.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install org.yourorg.cnfgtest without first uninstalling.]
make: *** [Makefile:167: push] Error 1
```

make clean and retrying doesn't work.

Phone LG K11 alpha
Android 7.1.2

**Comment by dreua** [comment]
Yeah you need to uninstall ist first, `make uninstall`. I think this could be made more user friendly by adding this step to `push` and/or `run`. Not sure if there is any reason not to do that. In the meantime I'd recommend `make uninstall && make run` (or push, whatever you use).

**Comment by dreua** [comment]
The `make run` should really be possible without uninstalling first. @cnlohr  how about just removing the `push` call here?

**Comment by dreua** [comment]
For the instacrash we'd need the logs: Either use Android studios built in logger or try `adb logcat | grep cnfgtest` (in another terminal).
