### ISSUE TITLE
Logcat spam (BufferQueueProducer) when suspended

### ISSUE THREAD

**Issue by dreua** [cnlohr/rawdrawandroid#21]
Steps to reproduce:
1. run `adb logcat | grep cnfgtest`
2. run rawdrawandroid in another shell
3. suspend the app, for example go to the homescreen
4. Log is printing this message at a high rate:

```
07-25 01:28:34.392   469  3410 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
07-25 01:28:34.409   469   507 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
07-25 01:28:34.409   469  2856 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
07-25 01:28:34.428   469   507 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
07-25 01:28:34.429   469  2856 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
07-25 01:28:34.446   469  3410 E BufferQueueProducer: [org.yourorg.cnfgtest/android.app.NativeActivity] dequeueBuffer: BufferQueue has no connected producer
```

When closing the app (via recent tasks) it stops. Not sure if this is specific to my Android version / device.

**Comment by cnlohr** [comment]
I think this looks like it might be related to the accelerometer... Not sure.

**Comment by cnlohr** [comment]
I don't actually know how to fix this - if you can investigate, I am def up for some PRs.

**Comment by DavidVentura** [comment]
I've spent some time looking at this; the minimum code that triggers this is
```c
int main( int argc, char ** argv )
{
        CNFGBGColor = 0x000040ff;
        CNFGSetupFullscreen( "Test Bench", 0 );
        while(1)
        {
                CNFGHandleInput();
                CNFGSwapBuffers();

        }
}
```

`CNFGHandleInput` is necessary to process Android events - otherwise the app is just busy looping.

Commenting out `CNFGSwapBuffers` makes the issue go away.
I have a "working" demo, but I am not sure if it's correct.. it does work on my phone!

**Comment by dreua** [comment]
I think this is solved then, thanks @DavidVentura !
