### ISSUE TITLE
SFML

### ISSUE THREAD

**Issue by ManuelDavideUrpi** [cnlohr/rawdrawandroid#26]
Is there any way to use the **SFML** library?

**Comment by dreua** [comment]
I just had a quick read and it sounds like it is a similar project to rawdraw, roughly speaking. Can you expand your idea some more? How exactly would you like to combine Sfml with rawdraw? Use Sfml as a drawing backend or the other way around, use it to draw videos inside rawdraw?

**Comment by dreua** [comment]
Closing for lack of response, feel free to reopen
