### ISSUE TITLE
package="${PACKAGENAME}" is left in AndroidManifest.xml

### ISSUE THREAD

**Issue by MobiusHorizons** [cnlohr/rawdrawandroid#31]
Following the instructions I ran 
```
make push run
```

after which I saw the following error message:
```
AndroidManifest.xml:2: Tag <manifest> attribute package has invalid character '$'.
```

It looks like a variable `package="${PACKAGENAME}"` was left un-replaced from the template.

looking at the Makefile:
```
	envsubst '$$ANDROIDTARGET $$ANDROIDVERSION $$APPNAME $$LABEL' \
		< AndroidManifest.xml.template > AndroidManifest.xml
```
it doesn't look like the package name is added for substitution.

**Comment by MobiusHorizons** [comment]
Update: I updated the line in the Makefile to specify the PROJECTNAME variable, but then I noticed that all the variables were getting written into the file as blanks. I don't know why this is, since it seems like the variables were getting exported correctly. I edited the file manually and it worked, but 
```
make -B AndroidManifest.xml
```
results in a broken manifest.

**Comment by cnlohr** [comment]
Do you have a github project I could try to pull and try out and see what's going on with?

**Comment by MobiusHorizons** [comment]
This was just after checking out the repo with no other modifications.

**Comment by cnlohr** [comment]
herp derp.... ok I think I see the issue.
