### ISSUE TITLE
Discord link in readme is broken

### ISSUE THREAD

**Issue by dev-kittens** [cnlohr/rawdrawandroid#33]
Hi! The link to the Discord server is broken again. Could it get updated? Thank you~

**Comment by suvidh** [comment]
yep! facing the same issue.

**Comment by AdamUnitE** [comment]
Ah, that invite code was never updated after _the incident._  Here is a new one: https://discord.com/invite/CCeyWyZ

**Comment by Indithem** [comment]
new invites?

**Comment by cnlohr** [comment]
Please DM me for one.  I'm `cnlohr` on Discord.

We require a link to one form of corroborating social, i.e. a github, youtube, twitter, etc. Due to *another incident*.

We are happy to accept new people! We may open up invites again at some point.
