### ISSUE TITLE
test.c:10:10: fatal error: 'asset_manager.h' file not found

### ISSUE THREAD

**Issue by muffledMitosis** [cnlohr/rawdrawandroid#40]
Hi! 

I have installed all the Sdk components and the NDK, but get this error when running `make push run`, cant for the life of me figure out whats up, ill add a screen shot of the full error below :)

Thank You!

![screenshot 1608096911](https://user-images.githubusercontent.com/45066995/102309423-a73af000-3f60-11eb-85fa-92eff2dc14d1.png)

**Comment by dreua** [comment]
I'd check that the file is in one of the include paths (`-I` arguments as listed in your screenshot). For me it's in `/home/da/Android/Sdk/ndk/21.1.6352462/sysroot/usr/include/android` (among others) so it should probably be in that path adapted to your username and ndk version.

**Comment by muffledMitosis** [comment]
> I'd check that the file is in one of the include paths (`-I` arguments as listed in your screenshot). For me it's in `/home/da/Android/Sdk/ndk/21.1.6352462/sysroot/usr/include/android` (among others) so it should probably be in that path adapted to your username and ndk version.

I did `find ~/Android/Sdk/ndk/22.0.7026061/* | grep "asset_manager.h"` and found it at `~/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/asset_manager.h`

![screenshot 1608172930](https://user-images.githubusercontent.com/45066995/102436921-7f579500-4011-11eb-82ea-ac9fb7489f22.png)

changing line 84 of the makefile to be
`CFLAGS+= -I$(RAWDRAWANDROID)/rawdraw -I$(NDK)/sysroot/usr/include -I$(NDK)/toolchains/llvm/prebuilt/$(OS_NAME)/sysroot/usr/include/a
    ndroid -fPIC -I$(RAWDRAWANDROID) -DANDROIDVERSION=$(ANDROIDVERSION)` fixed the issue
