### ISSUE TITLE
Please add online build

### ISSUE THREAD

**Issue by graysuit** [cnlohr/rawdrawandroid#44]
Respected developer @cnlohr,

Please show folks how to build rawdrawandroid using github actions live.
https://github.com/cnlohr/rawdrawandroid/actions

It supports linux,mac,windows with compiler of your choice. Compiles in seconds. And also tells the errors which users may face. I can also help in this process. Thanks.

Regards.

**Comment by dreua** [comment]
Hey, I'm planning to work on this in the next weeks but any help is welcome! I gave it a first try in [my branch](https://github.com/dreua/rawdrawandroid/tree/gh-action-build/.github/workflows) but it seems that my attempt without a dedicated container is not going to work. Maybe it's easiest if we build and test this in my fork and merge it to rawdrawandroid once it's relatively stable, what do you think?

**Comment by graysuit** [comment]
@dreua 
Sure
instead of `apt install`, use `sudo apt install`, or `sudo bash & apt install` or `sudo su & apt install` ...
and also share rawandroid compilation script, after i can easily build and create PR.

**Comment by dreua** [comment]
Thanks, I was assuming this would work like a Docker container without the need for sudo, turns out I was wrong.

**Comment by graysuit** [comment]
1 more thing you can improve, no need `sudo apt-get update` as you are already using `runs-on: ubuntu-latest`.
:)

**Comment by dreua** [comment]
@graysuit  thanks for your help!

I think the workflow is now downloading and installing all the dependencies on each run. This feels like a waste of time and resources to me but it might just be the best practice for Github workflows for some reason: Any strong opinions or further insights into this topic?

**Comment by graysuit** [comment]
Github workflow is VPS, means it can download/execute things under seconds. You should NOT care, github is funded by Microsoft. :)
This workflow will
- remove the need of installing compilation tools
- show result/state under seconds
- shows how to build 

most other companies do use same technique like libvlc uses azure pipelines to automatically build binaries.

I recommend to upload lib as well, *.so files. in different cpu architectures.

**Comment by dreua** [comment]
Thanks, fair point that it's only burning Microsofts money, I can live with that 😆 

About uploading .so files: I don't really see a use case in that because you would need the whole tool chain to use those anyway, don't you? Either convince me with a good user story or, even better, send a PR with the necessary changes. I'll try to review and merge that on short notice.

**Comment by graysuit** [comment]
Okay I show you convince power.

Okay tell me what is rawdrawandroid is mainly used for ? To draw raw graphics, right ?
And we know that rawdrawandroid type is `library`, its NOT `app` or `tool`.
And who uses rawdrawandroid ? Obviously, programmers. Normal user even don't know what its name mean. lol

So if it is **lib** and intended for **programmer** use, we must deliver lib, so that programmers may able to just import these *.so files and use it directly.
Imagine, how amazing it would be if it get used by android studio,flutter,xamarin,basic4android **non-ndk** projects etc.

They already have many options instead of rawdraw. But they will have to use rawdraw if they need NATIVE performance. Java based UI is useless in terms of performance.

wait I share PR.

**Comment by graysuit** [comment]
#46
