### ISSUE TITLE
Example sound_android.c is not found

### ISSUE THREAD

**Issue by abhra0897** [cnlohr/rawdrawandroid#45]
In the section **[If you are going to use this](https://github.com/cnlohr/rawdrawandroid#if-you-are-going-to-use-this)** , the URL of `sound_android.c` ( https://github.com/cnlohr/colorchord/blob/master/colorchord2/sound_android.c) is invalid. I searched but it seems the file doesn't exist anywhere.

**Comment by cnlohr** [comment]
It's probably referring to CNFA's android audio port. https://github.com/cntools/cnfa/blob/aa931ed2db1991381867a1722b0e6a7bac98f467/CNFA_android.c

**Comment by abhra0897** [comment]
Thanks for pointing out.
