### ISSUE TITLE
Does this mean that Android can be used for real-time computing?

### ISSUE THREAD

**Issue by mavavilj** [cnlohr/rawdrawandroid#48]
Does this mean that Android can be used for real-time computing?

https://ieeexplore.ieee.org/document/6454350

**Comment by dreua** [comment]
I don't See how this is related to rawdrawandroid.
Furtermore the last Paragraph oft the abstract sounds like the answer is no.

**Comment by mavavilj** [comment]
It's related in the sense that I was looking for rawdrawandroid to implement a C/C++ app without Java and its GC. Then in reference to the Oboe C++ library I thought that this would allow e.g. C++ level audio I/O latency. If it doesn't pass through the JVM and JNI, then I thought this library would be as fast as native C/C++ on desktop.

**Comment by mavavilj** [comment]
The paper also gives infor in the last paragraph regarding potential solutions, so perhaps this library does not in fact change anything about Android, but just programs it in C/C++.

**Comment by mavavilj** [comment]
I still wonder though, whether this allows it so that there's no latency induced by the JNI? In other words, if one writes a GUI with this and e.g. signal processing using some C library, then all calls between the GUI and the DSP would have no added latency between except for those produced by C code.

**Comment by dreua** [comment]
I understand your question now, unfortunately there seems to be no one here who has the answer. AFAIK, RT was never a goal of this project.

**Comment by MatejMagat305** [comment]
I think that It is almost 100% true that pure C will not have GC latency and at certain will have less RAM consumtion and will be more realtime than java

**Comment by dreua** [comment]
I think this is answered as far as possible.
