### ISSUE TITLE
How can I change the default font of rawdrawandroid?

### ISSUE THREAD

**Issue by imp-sike** [cnlohr/rawdrawandroid#50]
Is it possible to change the font of rawdrawandoid to some of modern fonts like Poppins, Ubuntu, etc. If yes, how can i do it. The current font is awsome for games but for a minimal app, modern fonts like Poppins are more preferred, so please guide me to change it.

**Comment by dreua** [comment]
Afaik, the font is custom made and lives in [CNFGFunctions.c](https://github.com/cntools/rawdraw/blob/e352fc1dfb050a30aa5b86c4943dda5c30790316/CNFGFunctions.c#L39) i.e. it can not be easily replaced by a regular font.
