### ISSUE TITLE
Android 24 ?

### ISSUE THREAD

**Issue by Blimp01** [cnlohr/rawdrawandroid#53]
Hello,

In the readme file it says to select Android 24, i cant seem to find that is it a mistype ?

thanks

Blimp

**Comment by dreua** [comment]
Pretty sure that should say API level 24 which was Android 7: https://developer.android.com/studio/releases/platforms

This is probably end of life and might not be available any more. In general this project can require a bit of trial an error on your side, its not that heavily used and maintained tbh. There might be people on cnlohrs Discord who could help.

The CI seems to run with API version 30:
https://github.com/cnlohr/rawdrawandroid/blob/971be12a3ee18c6ab1c5db150a824fc8a325e0c5/.github/workflows/install.yml#L45

I'm currently not using this project myself but I can review and merge PRs, so if you like to update/improve the Readme or anything else that's always appreciated.

**Comment by Blimp01** [comment]
Hi thanks for getting back to me! 

Sorry was looking at Android number not the API number, but you are correct got it working for android API 30 

Thanks
