### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/rawdrawandroid#70]
@dreua any chance you could look at why the CI is broken?  The error is nonobvious to me.

**Comment by dreua** [comment]
It consistently failed at:
```
[===                                    ] 8% Computing updates...               
Warning: Failed to find package 'patcher;v4'
[===                                    ] 10% Computing updates...              
                                                                                
[===                                    ] 10% Computing updates...              
Error: Process completed with exit code 1.
```

It just said warming but maybe this is actually an error? Do you know what this patcher is and maybe if we can use it in another version?

**Comment by dreua** [comment]
Tried it wothou a version but that also failed, removing patcher it is green. Do we need this package?
