### ISSUE TITLE
README link to permissions request code 404s

### ISSUE THREAD

**Issue by avelican** [cnlohr/rawdrawandroid#77]
In "If you are going to use this section", this link 404s:
https://github.com/cnlohr/colorchord/blob/master/colorchord2/sound_android.c

As far as I can tell, the relevant code is here:
https://github.com/cntools/cnfa/blob/d271e0196d81412032eeffa634a94a1aaf0060a7/CNFA_android.c#L305
```
int hasperm = AndroidHasPermissions( "RECORD_AUDIO" );
if( !hasperm )
{
	AndroidRequestAppPermissions( "RECORD_AUDIO" );
}
```

Also, if that's all the code, it might be helpful to put a little code block in the README.

**Comment by cnlohr** [comment]
Yes, that is the correct code. I will update readme.
