### ISSUE TITLE
can this work in cygwin

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [cnlohr/rawdrawandroid#84]
would possible to use this from cygwin? because i want to try it... but it must work from windows 7 32bit... otherwise it's pointless

**Comment by cnlohr** [comment]
I don't think this can work in cygwin, since it relies on the android compiler.

**Comment by MyTDT-Mysoft** [comment]
ok... but the android compiler didnt required wsl last time i tried building... it worked fine from cmd... so then it may not need cygwin and work directly from cmd
